blood_volume: [heart]
venous_return: [heart]
cardiac_filling: [heart]
contractility: [heart]
stroke_volume: [heart]
heart_rate: [heart]
cardiac_output: [vasculature]
vascular_tone: [vasculature]
systemic_vascular_resistance: [vasculature]
mean_arterial_pressure: [kidney, sympathetic, adh]
sympathetic_activity: [heart, vasculature, kidney]
renal_perfusion: [kidney]
GFR: [kidney]
sodium_reabsorption: [kidney]
urine_output: [blood]
renin: [raas]
angiotensin_II: [vasculature, adh]
aldosterone: [kidney]
ADH: [vasculature, kidney]
plasma_osmolality: [adh]
