import argparse
import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
import yaml
from pydantic import BaseModel, ConfigDict, model_validator

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from src.llm import LLM

EXTRACTION_SYSTEM_PROMPT = """
You extract local physiological knowledge from one chapter of a medical textbook.

The target model contains multiple organ or tissue modules. Each module is treated as a local
dynamical system with four kinds of knowledge:

State
  Local states, stores, structures, processes, and molecular machinery owned by the module.

Inputs
  External signals, substances, or conditions that reach the module.

Dynamics
  How inputs are sensed and how they change local states through mechanisms owned by the module.

Outputs
  Changes generated by the module that are exposed at its boundary, such as secretion, release,
  uptake, clearance, transport, contraction, or neural discharge.

A chapter may contain knowledge about multiple modules. Produce one separate knowledge file for each
module that the chapter meaningfully contributes to.

Each knowledge file belongs to exactly one module.

Use only module ids from the provided module list.

# Locality

Describe only states, mechanisms, and actions owned by the module.

External organs, circulating substances, and physiological states may appear as inputs, sources,
routes, or anatomical context.

Stop causal reasoning at the module's own output boundary.

# Knowledge style

Write concise, self-contained bullet points.

Each bullet should express one physiological fact, local mechanism, or boundary action.

Prefer short statements over textbook-style explanations. Split long statements when they contain
multiple distinct facts or mechanisms.

Preserve mechanistic, conditional, or quantitative detail only when it helps determine how the
module responds to an input or intervention.

Do not compress a stated mechanism into a vague summary when the mechanism is important for reasoning
about interventions.

# Extraction

State:
Include local states, stores, structures, processes, receptors, transporters, enzymes, channels, and
other machinery that are relevant to the module's physiological behavior.

Inputs:
Include external signals, substances, or conditions that directly reach or act on the module.

Dynamics:
Describe how inputs are sensed and how they change local states through receptors, transporters,
enzymes, channels, signaling pathways, cellular processes, or other local mechanisms.

Keep conditions such as fed versus fasting, acute versus chronic, thresholds, saturation, dose
dependence, and timescales when they materially change the response.

Outputs:
Describe only boundary changes directly generated by the module. Keep outputs short and stop before
describing downstream effects.

Use only knowledge supported by this chapter. Do not add outside biological knowledge.

# Output

Return zero or more knowledge files.

Each knowledge file must contain:

module_id: <module_id>

### State
- ...

### Inputs
- ...

### Dynamics
- ...

### Outputs
- ...

Omit empty sections.

Omit modules for which the chapter provides no meaningful knowledge.

"""

JUDGE_SYSTEM_PROMPT = """You check whether one organ or tissue knowledge file respects its local ownership boundary.

You receive:
- the module_id
- the complete knowledge file

A knowledge file is local when every change it attributes to the module is a change in a state,
process, mechanism, or boundary action owned by that module.

External organs, circulating substances, and physiological states may appear as inputs, sources,
routes, or anatomical context.

An output generated by the module at its boundary, such as secretion, release, uptake, clearance,
transport, contraction, or neural discharge, is local.

Leakage occurs when the knowledge:
- attributes a change to another module, circulation, or the whole body, or
- describes a local mechanism that is owned by a different module.

For each violation:
- quote the shortest exact span that violates locality
- briefly explain why it is non-local
- give the smallest edit needed to fix it

Return JSON only:

{
  "has_leakage": true | false,
  "violations": [
    {
      "span": "exact text from the knowledge file",
      "reason": "brief explanation",
      "fix": "minimal edit instruction"
    }
  ]
}

Set "has_leakage" to false when there are no violations.
"""

REPAIR_SYSTEM_PROMPT = """You repair one organ or tissue knowledge file using a locality judgment.

You receive:
- the original complete knowledge file
- the judge's violations

Apply only the supplied locality fixes.

Preserve all valid local knowledge.

Make the smallest changes necessary to remove the reported leakage.

Allowed edits:
- delete a leaking span
- truncate reasoning at the module boundary
- minimally rewrite a sentence when necessary to remove a leaking consequence

Do not add new medical knowledge or infer new consequences.

Preserve valid mechanisms, molecular detail, quantitative values, conditions, headings, and overall
structure.

Return the complete repaired knowledge file in the same format as the original.
"""


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class KnowledgeFile(StrictModel):
    module_id: str
    knowledge: str


class ExtractedKnowledge(StrictModel):
    knowledge_files: list[KnowledgeFile]


class LeakageViolation(StrictModel):
    span: str
    reason: str
    fix: str


class LeakageJudgment(StrictModel):
    has_leakage: bool
    violations: list[LeakageViolation]

    @model_validator(mode="after")
    def validate_verdict(self):
        if self.has_leakage != bool(self.violations):
            raise ValueError("has_leakage must match whether violations is empty")
        return self


@dataclass
class ModuleResult:
    module_id: str
    extracted: str
    judgment: LeakageJudgment
    final: str
    calls: list


@dataclass
class ExtractionResult:
    extraction: ExtractedKnowledge
    modules: list[ModuleResult]
    calls: list


class KnowledgeExtractionPipeline:
    def __init__(self, llm, modules):
        self.llm = llm
        self.modules = modules

    def run(self, chapter_prompt):
        extraction = self.extract(chapter_prompt)
        modules = []
        calls = [extraction]
        for knowledge_file in extraction.value.knowledge_files:
            judgment = self.judge(knowledge_file)
            final = knowledge_file.knowledge
            module_calls = [judgment]
            if judgment.value.has_leakage:
                repair = self.repair(knowledge_file, judgment.value)
                final = repair.value.knowledge
                module_calls.append(repair)
            modules.append(
                ModuleResult(
                    knowledge_file.module_id,
                    knowledge_file.knowledge,
                    judgment.value,
                    final,
                    module_calls,
                )
            )
            calls.extend(module_calls)
        return ExtractionResult(extraction.value, modules, calls)

    def extract(self, chapter_prompt):
        completion = self.llm.generate(
            EXTRACTION_SYSTEM_PROMPT,
            chapter_prompt,
            ExtractedKnowledge,
        )
        self._validate_extraction(completion.value)
        return completion

    def judge(self, knowledge_file):
        completion = self.llm.generate(
            JUDGE_SYSTEM_PROMPT,
            self._judge_prompt(knowledge_file),
            LeakageJudgment,
        )
        self._validate_judgment(knowledge_file.knowledge, completion.value)
        return completion

    def repair(self, knowledge_file, judgment):
        completion = self.llm.generate(
            REPAIR_SYSTEM_PROMPT,
            self._repair_prompt(knowledge_file, judgment),
            KnowledgeFile,
        )
        if completion.value.module_id != knowledge_file.module_id:
            raise ValueError("repair changed module_id")
        return completion

    def _judge_prompt(self, knowledge_file):
        return (
            f"module_id: {knowledge_file.module_id}\n\n"
            f"Complete knowledge file:\n\n{knowledge_file.knowledge}"
        )

    def _repair_prompt(self, knowledge_file, judgment):
        feedback = json.dumps(judgment.model_dump(), indent=2, ensure_ascii=False)
        return (
            f"module_id: {knowledge_file.module_id}\n\n"
            f"Locality judgment:\n{feedback}\n\n"
            f"Original complete knowledge file:\n\n{knowledge_file.knowledge}"
        )

    def _validate_extraction(self, extraction):
        known = {module["id"] for module in self.modules}
        module_ids = [knowledge_file.module_id for knowledge_file in extraction.knowledge_files]
        duplicates = {module_id for module_id in module_ids if module_ids.count(module_id) > 1}
        if duplicates:
            raise ValueError(f"extractor returned duplicate modules: {sorted(duplicates)}")
        unknown = set(module_ids) - known
        if unknown:
            raise ValueError(f"extractor returned unknown modules: {sorted(unknown)}")

    def _validate_judgment(self, knowledge, judgment):
        for violation in judgment.violations:
            if violation.span not in knowledge:
                raise ValueError(
                    f"judge returned a span absent from extracted knowledge: {violation.span}"
                )


def load_yaml(path):
    return yaml.safe_load((ROOT / path).read_text())


def load_profile(path):
    profile = load_yaml(path)
    required = ("book", "output", "modules", "scenarios", "model", "generation")
    missing = [key for key in required if key not in profile]
    if missing:
        raise ValueError(f"extraction profile is missing required keys: {missing}")
    return profile


def validate_profile(profile, chapters):
    required = ("id", "group", "description", "primary", "supporting")
    for module in profile["modules"]:
        missing = [key for key in required if key not in module]
        if missing:
            raise ValueError(f"module is missing required keys: {missing}")
    ids = [module["id"] for module in profile["modules"]]
    duplicates = {module_id for module_id in ids if ids.count(module_id) > 1}
    if duplicates:
        raise ValueError(f"duplicate module ids: {sorted(duplicates)}")
    known = set(chapters)
    for module in profile["modules"]:
        unknown = set(module["primary"] + module["supporting"]) - known
        if unknown:
            raise ValueError(f"module '{module['id']}' cites missing chapters {sorted(unknown)}")
        if not module["primary"]:
            raise ValueError(f"module '{module['id']}' has no primary chapter")
    unknown_scenarios = set(profile["scenarios"]) - known
    if unknown_scenarios:
        raise ValueError(f"missing scenario chapters: {sorted(unknown_scenarios)}")


def chapter_assignments(profile):
    mapping = defaultdict(dict)
    for module in profile["modules"]:
        for role in ("primary", "supporting"):
            for number in module[role]:
                mapping[number].setdefault(module["id"], role)
    return mapping


def strip_frontmatter(text):
    if not text.startswith("---\n"):
        raise ValueError("chapter file has no frontmatter")
    return text.split("\n---\n", 1)[1].lstrip("\n")


def build_chapter_prompt(profile, chapter, roles, text):
    listing = "\n".join(
        f"{'*' if module['id'] in roles else ' '} {module['id']} - {module['description']}"
        for module in profile["modules"]
    )
    return (
        f"Book: {chapter['book']}\n"
        f"Unit: {chapter['unit']}\n"
        f"Chapter {chapter['number']}: {chapter['title']}\n\n"
        f"Available modules. This chapter is expected to contribute to the starred ones, but write to"
        f" any module the chapter genuinely describes:\n{listing}\n\n"
        f"Chapter text:\n\n{text}"
    )


def save_hierarchy(output, profile, index, mapping):
    chapters = {chapter["number"]: chapter for chapter in index["chapters"]}
    hierarchy = {
        "book": index["book"],
        "groups": sorted({module["group"] for module in profile["modules"]}),
        "modules": profile["modules"],
        "chapters": {
            str(number): {
                "title": chapters[number]["title"],
                "characters": chapters[number]["characters"],
                "modules": roles,
            }
            for number, roles in sorted(mapping.items())
        },
        "scenarios": {
            str(number): chapters[number]["title"]
            for number in profile["scenarios"]
        },
    }
    output.mkdir(parents=True, exist_ok=True)
    (output / "hierarchy.json").write_text(
        json.dumps(hierarchy, indent=2, ensure_ascii=False) + "\n"
    )


def save_prompt(output, chapter, prompt):
    prompts = output / "prompts"
    prompts.mkdir(parents=True, exist_ok=True)
    (prompts / "extractor_system.txt").write_text(EXTRACTION_SYSTEM_PROMPT.strip() + "\n")
    path = prompts / f"ch{chapter:02d}.txt"
    path.write_text(prompt)
    return path


def render_knowledge_file(knowledge_file):
    return f"module_id: {knowledge_file.module_id}\n\n{knowledge_file.knowledge.rstrip()}\n"


def save_trace(destination, completion):
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "trace.json").write_text(
        json.dumps(completion.dump(), indent=2, ensure_ascii=False) + "\n"
    )


def save_extraction(destination, completion):
    save_trace(destination, completion)
    for knowledge_file in completion.value.knowledge_files:
        (destination / f"{knowledge_file.module_id}.md").write_text(
            render_knowledge_file(knowledge_file)
        )


def save_judgment(destination, completion):
    save_trace(destination, completion)
    (destination / "result.json").write_text(
        completion.value.model_dump_json(indent=2) + "\n"
    )


def save_repair(destination, completion):
    save_trace(destination, completion)
    (destination / "result.md").write_text(
        render_knowledge_file(completion.value)
    )


def run_chapter(pipeline, prompt, destination, extract_only):
    destination.mkdir(parents=True, exist_ok=True)
    extraction = pipeline.extract(prompt)
    save_extraction(destination / "extractor", extraction)
    if extract_only:
        return extraction.value, []

    final = destination / "final"
    final.mkdir(exist_ok=True)
    judgments = []
    for knowledge_file in extraction.value.knowledge_files:
        judgment = pipeline.judge(knowledge_file)
        save_judgment(destination / "judge" / knowledge_file.module_id, judgment)
        judgments.append(judgment.value)
        knowledge = knowledge_file.knowledge
        if judgment.value.has_leakage:
            repair = pipeline.repair(knowledge_file, judgment.value)
            save_repair(destination / "repair" / knowledge_file.module_id, repair)
            knowledge = repair.value.knowledge
        completed = KnowledgeFile(module_id=knowledge_file.module_id, knowledge=knowledge)
        (final / f"{knowledge_file.module_id}.md").write_text(
            render_knowledge_file(completed)
        )
    return extraction.value, judgments


def main():
    parser = argparse.ArgumentParser(
        description="Extract chapter knowledge, judge locality once, and repair leakage once"
    )
    parser.add_argument("profile")
    selection = parser.add_mutually_exclusive_group(required=True)
    selection.add_argument("--chapters", nargs="+", type=int)
    selection.add_argument("--all-mapped", action="store_true")
    execution = parser.add_mutually_exclusive_group()
    execution.add_argument("--prepare-only", action="store_true")
    execution.add_argument("--extract-only", action="store_true")
    args = parser.parse_args()

    profile = load_profile(args.profile)
    book = load_yaml(profile["book"])
    index = json.loads((ROOT / book["output"] / "index.json").read_text())
    chapters = {chapter["number"]: chapter for chapter in index["chapters"]}
    validate_profile(profile, chapters)
    mapping = chapter_assignments(profile)
    selected = sorted(mapping) if args.all_mapped else args.chapters
    unknown = set(selected) - set(mapping)
    if unknown:
        raise ValueError(f"chapters are not mapped to any module: {sorted(unknown)}")

    output = ROOT / profile["output"]
    save_hierarchy(output, profile, index, mapping)
    prompts = {}
    for number in selected:
        chapter = dict(chapters[number], book=index["book"])
        text = strip_frontmatter((ROOT / book["output"] / chapter["file"]).read_text())
        prompt = build_chapter_prompt(profile, chapter, mapping[number], text)
        path = save_prompt(output, number, prompt)
        prompts[number] = prompt
        print(f"ch{number:02d}  prompt -> {path.relative_to(ROOT)}")
    if args.prepare_only:
        return

    llm = LLM(profile)
    pipeline = KnowledgeExtractionPipeline(llm, profile["modules"])
    for number, prompt in prompts.items():
        destination = output / "results" / f"ch{number:02d}"
        extraction, judgments = run_chapter(
            pipeline,
            prompt,
            destination,
            args.extract_only,
        )
        if args.extract_only:
            print(f"ch{number:02d}  extractor -> {(destination / 'extractor').relative_to(ROOT)}")
            continue
        repaired = sum(judgment.has_leakage for judgment in judgments)
        print(f"ch{number:02d}  {len(extraction.knowledge_files)} modules, {repaired} repaired")


if __name__ == "__main__":
    main()
